config = {
    'EXP_NAME': "phase2_covid_(24-7)_TL",
    'EXP_PHASE': "phase2",
    'EXP_GROUP': "covid",
    'AUGMENT_DATA': True,
    'ONLY_NIGHT_DATA': False,
    'MODEL_DIR': None,
    'TRAIN_VAE': True,
    'TRAIN_LSTM': True,
    'LEN_WIN': 24,
    'N_WIN': 7,
    'LATENT_DIM': 6,
    'BATCH_SIZE': 64,
    'VAL_SPLIT': 0.05,
    'LEARNING_RATE': 0.0002,
    'EPOCH': 1,
    'PATIENCE': 10,
}
