config = {
    'EXP_NAME': "PCovNet_phase2_covid",
    'EXP_PHASE': "phase2",
    'EXP_GROUP': "covid",
    'AUGMENT_DATA': True,
    'ONLY_NIGHT_DATA': False,
    'MODEL_DIR': None,
    'TRAIN_VAE': True,
    'TRAIN_LSTM': True,
    'LEN_WIN': 8,
    'N_WIN': 2,
    'LATENT_DIM': 16,
    'BATCH_SIZE': 64,
    'VAL_SPLIT': 0.05,
    'LEARNING_RATE': 0.0002,
    'EPOCH': 1000,
    'PATIENCE': 10,
}
